# This is a basic workflow to help you get started with Actions

name: Test-Workflow
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: test-branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd TelegramMoviesBot
          dotnet restore TelegramMoviesBot.csproj
      - name: build project
        run: |
          cd TelegramMoviesBot
          dotnet build TelegramMoviesBot.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
         Dockerfile: ${{ secrets.DOCKERFILE_RAW_URL }}
         TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
         TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.REMOTE_PORT }}
         envs: Dockerfile,TELEGRAM_API_KEY,TMDB_API_KEY
         script: |
            env
            rm Dockerfile
            echo "$Dockerfile" > DockerfileURL
            cat DockerfileURL
            wget $Dockerfile
            docker kill TelegramMoviesBot
            docker image rm maior1998:TelegramMoviesBot
            docker build -t maior1998:TelegramMoviesBot .
          
            
            
      
